### ISSUE TITLE
AttributeError: 'bitarray.bitarray' object has no attribute 'length'

### ISSUE THREAD

**Issue by Asifadb** [NixName420/BTC-InfoStar#1]
what is btc.bf file in the code?

**Comment by Blythex** [comment]
use the btc.bf without balance from this telegramchannel i use it to 

https://t.me/Blockchain_BTC_ETH_DUMPS

> what is btc.bf file in the code?

**Comment by Blythex** [comment]
pip install bitarray==1.9.2

AttributeError: 'bitarray.bitarray' object has no attribute 'length' #1****
