### ISSUE TITLE
choice 9 pvtkeys between publickeranges no working

### ISSUE THREAD

**Issue by Asifadb** [NixName420/BTC-InfoStar#2]
Your choice: 9
Enter the starting value of the public key: 03633cbe3ec02b9401c5effa144c5b4d22f87940259634858fc7e59b1c09937852
Enter the ending value of the public key: 0233709eb11e0d4439a729f21c2c443dedb727528229713f0065721ba8fa46f00e
Do you want to display the progress bar? (y/n): y
Generating and saving keys: 0it [00:00, ?it/s]

**Comment by NixName420** [comment]
Your choice: 9
Note: Ensure that both the start and end public keys are either both compressed or both uncompressed.
Compressed keys start with '02' or '03' and have a length of 66 characters. Uncompressed keys start with '04' and have a length of 130 characters.
Type 'back' to return to the main menu at any time.
Enter the starting value of the public key: 0233709eb11e0d4439a729f21c2c443dedb727528229713f0065721ba8fa46f00e
Enter the ending value of the public key: 03633cbe3ec02b9401c5effa144c5b4d22f87940259634858fc7e59b1c09937852
Do you want to display the progress bar? (y/n): y
Gefundene Adressen: 0 | Verstrichene Zeit: 0:00:10.653454 | Adressen generiert und gespeichert: 39074


its working bro

**Comment by Blythex** [comment]
> Your choice: 9 Enter the starting value of the public key: 03633cbe3ec02b9401c5effa144c5b4d22f87940259634858fc7e59b1c09937852 Enter the ending value of the public key: 0233709eb11e0d4439a729f21c2c443dedb727528229713f0065721ba8fa46f00e Do you want to display the progress bar? (y/n): y Generating and saving keys: 0it [00:00, ?it/s]




Enter the starting value of the public key: 0233709eb11e0d4439a729f21c2c443dedb727528229713f0065721ba8fa46f00e
Enter the ending value of the public key: 03633cbe3ec02b9401c5effa144c5b4d22f87940259634858fc7e59b1c09937852
Do you want to display the progress bar? (y/n): y
Gefundene Adressen: 0 | Verstrichene Zeit: 0:01:51.470928 | Adressen generiert und gespeichert: 409559
User interrupted the process.

Generated keys have been saved in 'public_key_range_data_4.json'.
